name: schedulemanager
description: "Schedule manager MVP with Flutter, Riverpod, and Firebase."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  firebase_core: ^2.30.1
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.17.3
  table_calendar: ^3.0.9
  intl: ^0.18.1
  uuid: ^4.4.2

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
